-- better-effect-mq PostgreSQL protocol schema, migration 1.
-- The adapter substitutes {{SCHEMA}} with one validated, quoted identifier.

CREATE TABLE IF NOT EXISTS {{SCHEMA}}.better_effect_mq_jobs (
  namespace text NOT NULL,
  id text NOT NULL,
  queue text NOT NULL,
  name text NOT NULL,
  version bigint NOT NULL,
  state text NOT NULL,
  payload jsonb NOT NULL,
  metadata jsonb NOT NULL,
  priority bigint NOT NULL,
  run_at_ms bigint NOT NULL,
  sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  attempts_max bigint NOT NULL,
  attempts_made bigint NOT NULL,
  delivery_count bigint NOT NULL,
  stalled_count bigint NOT NULL,
  attempt_sequence bigint NOT NULL DEFAULT 0,
  backoff jsonb,
  timeout_ms bigint,
  idempotency_key text,
  dedupe_key text,
  created_at_ms bigint NOT NULL,
  updated_at_ms bigint NOT NULL,
  processed_at_ms bigint,
  finished_at_ms bigint,
  lease_owner text,
  lease_token text,
  lease_expires_at_ms bigint,
  cancel_requested boolean NOT NULL DEFAULT false,
  cancellation_requested_at_ms bigint,
  result jsonb,
  failure jsonb,
  last_settlement_token text,
  last_settlement_outcome text,
  last_settlement_attempt_sequence bigint,
  PRIMARY KEY (namespace, id),
  CONSTRAINT better_effect_mq_jobs_nonempty CHECK (
    namespace <> '' AND id <> '' AND queue <> '' AND name <> ''
  ),
  CONSTRAINT better_effect_mq_jobs_state CHECK (
    state IN ('waiting', 'delayed', 'active', 'completed', 'failed', 'cancelled')
  ),
  CONSTRAINT better_effect_mq_jobs_version CHECK (version > 0),
  CONSTRAINT better_effect_mq_jobs_counters CHECK (
    attempts_max >= 1 AND attempts_made >= 0 AND attempts_made <= attempts_max
    AND attempts_made <= delivery_count
    AND delivery_count >= 0 AND stalled_count >= 0 AND attempt_sequence >= attempts_made
    AND (state NOT IN ('waiting', 'delayed', 'active') OR attempts_made < attempts_max)
    AND (state <> 'active' OR attempts_made < delivery_count)
  ),
  CONSTRAINT better_effect_mq_jobs_epoch_ms CHECK (
    run_at_ms BETWEEN 0 AND 9007199254740991
    AND created_at_ms BETWEEN 0 AND 9007199254740991
    AND updated_at_ms BETWEEN 0 AND 9007199254740991
    AND (timeout_ms IS NULL OR timeout_ms BETWEEN 1 AND 9007199254740991)
    AND (processed_at_ms IS NULL OR processed_at_ms BETWEEN 0 AND 9007199254740991)
    AND (finished_at_ms IS NULL OR finished_at_ms BETWEEN 0 AND 9007199254740991)
    AND (lease_expires_at_ms IS NULL OR lease_expires_at_ms BETWEEN 0 AND 9007199254740991)
    AND (cancellation_requested_at_ms IS NULL OR cancellation_requested_at_ms BETWEEN 0 AND 9007199254740991)
  ),
  CONSTRAINT better_effect_mq_jobs_metadata_values CHECK (
    jsonb_typeof(metadata) = 'object'
    AND NOT jsonb_path_exists(metadata, '$.* ? (@.type() != "string")')
  ),
  CONSTRAINT better_effect_mq_jobs_tokens CHECK (
    (idempotency_key IS NULL OR idempotency_key <> '')
    AND (dedupe_key IS NULL OR dedupe_key <> '')
    AND (lease_owner IS NULL OR lease_owner <> '')
    AND (lease_token IS NULL OR lease_token <> '')
    AND (last_settlement_token IS NULL OR last_settlement_token <> '')
  ),
  CONSTRAINT better_effect_mq_jobs_active_lease CHECK (
    (state = 'active' AND lease_owner IS NOT NULL AND lease_owner <> ''
      AND lease_token IS NOT NULL AND lease_token <> '' AND lease_expires_at_ms IS NOT NULL)
    OR (state <> 'active' AND lease_owner IS NULL AND lease_token IS NULL AND lease_expires_at_ms IS NULL)
  ),
  CONSTRAINT better_effect_mq_jobs_cancel_requested CHECK (
    cancel_requested = (cancellation_requested_at_ms IS NOT NULL)
    AND (state = 'active' OR cancellation_requested_at_ms IS NULL)
  ),
  CONSTRAINT better_effect_mq_jobs_terminal_time CHECK (
    state NOT IN ('completed', 'failed', 'cancelled') OR finished_at_ms IS NOT NULL
  ),
  CONSTRAINT better_effect_mq_jobs_settlement_pair CHECK (
    (last_settlement_token IS NULL AND last_settlement_outcome IS NULL AND last_settlement_attempt_sequence IS NULL)
    OR (last_settlement_token IS NOT NULL AND last_settlement_outcome IS NOT NULL AND last_settlement_attempt_sequence IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS {{SCHEMA}}.better_effect_mq_attempts (
  namespace text NOT NULL,
  job_id text NOT NULL,
  ledger_sequence bigint GENERATED ALWAYS AS IDENTITY,
  attempt_sequence bigint,
  attempt bigint NOT NULL,
  delivery bigint NOT NULL,
  started_at_ms bigint,
  finished_at_ms bigint NOT NULL,
  outcome text NOT NULL,
  result jsonb,
  failure jsonb,
  worker_id text,
  retry_at_ms bigint,
  retry_delay_ms bigint,
  PRIMARY KEY (namespace, job_id, ledger_sequence),
  CONSTRAINT better_effect_mq_attempts_job_fk FOREIGN KEY (namespace, job_id)
    REFERENCES {{SCHEMA}}.better_effect_mq_jobs(namespace, id) ON DELETE CASCADE,
  CONSTRAINT better_effect_mq_attempts_values CHECK (
    namespace <> '' AND job_id <> '' AND attempt >= 1 AND delivery >= 1
  ),
  CONSTRAINT better_effect_mq_attempts_outcome CHECK (
    outcome IN ('completed', 'retried', 'failed', 'cancelled', 'stalled', 'released')
  ),
  CONSTRAINT better_effect_mq_attempts_tokens CHECK (
    (worker_id IS NULL OR worker_id <> '')
  ),
  CONSTRAINT better_effect_mq_attempts_retry CHECK (
    (outcome = 'retried' AND retry_at_ms IS NOT NULL AND retry_delay_ms IS NOT NULL)
    OR (outcome <> 'retried' AND retry_at_ms IS NULL AND retry_delay_ms IS NULL)
  ),
  CONSTRAINT better_effect_mq_attempts_times CHECK (
    (started_at_ms IS NULL OR started_at_ms BETWEEN 0 AND 9007199254740991)
    AND finished_at_ms BETWEEN 0 AND 9007199254740991
    AND (retry_at_ms IS NULL OR retry_at_ms BETWEEN 0 AND 9007199254740991)
    AND (retry_delay_ms IS NULL OR retry_delay_ms BETWEEN 0 AND 9007199254740991)
    AND (attempt_sequence IS NULL OR attempt_sequence = attempt)
    AND (started_at_ms IS NULL OR started_at_ms <= finished_at_ms)
  )
);

CREATE TABLE IF NOT EXISTS {{SCHEMA}}.better_effect_mq_queues (
  namespace text NOT NULL,
  queue text NOT NULL,
  paused boolean NOT NULL DEFAULT false,
  wake_version bigint NOT NULL DEFAULT 0,
  updated_at_ms bigint NOT NULL,
  PRIMARY KEY (namespace, queue),
  CONSTRAINT better_effect_mq_queues_values CHECK (
    namespace <> '' AND queue <> '' AND wake_version BETWEEN 0 AND 9007199254740991
    AND updated_at_ms BETWEEN 0 AND 9007199254740991
  )
);

CREATE TABLE IF NOT EXISTS {{SCHEMA}}.better_effect_mq_schema_versions (
  component text PRIMARY KEY,
  version integer NOT NULL,
  applied_at_ms bigint NOT NULL,
  checksum text NOT NULL,
  CONSTRAINT better_effect_mq_schema_versions_values CHECK (
    component <> '' AND version >= 0 AND applied_at_ms BETWEEN 0 AND 9007199254740991
    AND checksum <> ''
  )
);

CREATE INDEX IF NOT EXISTS better_effect_mq_jobs_claim_idx
  ON {{SCHEMA}}.better_effect_mq_jobs
  (namespace, queue, state, priority DESC, run_at_ms ASC, sequence ASC, id COLLATE "C" ASC);
CREATE INDEX IF NOT EXISTS better_effect_mq_jobs_active_lease_idx
  ON {{SCHEMA}}.better_effect_mq_jobs
  (namespace, state, lease_expires_at_ms ASC)
  WHERE state = 'active';
CREATE INDEX IF NOT EXISTS better_effect_mq_jobs_identity_idx
  ON {{SCHEMA}}.better_effect_mq_jobs (namespace, queue, name, version, state);
CREATE INDEX IF NOT EXISTS better_effect_mq_jobs_recent_idx
  ON {{SCHEMA}}.better_effect_mq_jobs (namespace, created_at_ms DESC, sequence DESC, id COLLATE "C" DESC);
CREATE INDEX IF NOT EXISTS better_effect_mq_jobs_run_at_idx
  ON {{SCHEMA}}.better_effect_mq_jobs (namespace, queue, state, run_at_ms ASC, sequence ASC, id COLLATE "C" ASC);
CREATE INDEX IF NOT EXISTS better_effect_mq_jobs_terminal_idx
  ON {{SCHEMA}}.better_effect_mq_jobs (namespace, state, finished_at_ms DESC, sequence DESC, id COLLATE "C" DESC)
  WHERE state IN ('completed', 'failed', 'cancelled');
CREATE INDEX IF NOT EXISTS better_effect_mq_jobs_metadata_idx
  ON {{SCHEMA}}.better_effect_mq_jobs USING GIN (metadata jsonb_path_ops);
CREATE UNIQUE INDEX IF NOT EXISTS better_effect_mq_jobs_idempotency_idx
  ON {{SCHEMA}}.better_effect_mq_jobs (namespace, queue, name, version, dedupe_key)
  WHERE dedupe_key IS NOT NULL;
