-- better-effect-mq durable outbox extension, migration 3.
-- The adapter substitutes {{SCHEMA}} with one validated, quoted identifier.

CREATE TABLE IF NOT EXISTS {{SCHEMA}}.better_effect_mq_outbox (
  namespace text NOT NULL,
  id text NOT NULL,
  target text NOT NULL,
  protocol_version integer NOT NULL,
  state text NOT NULL,
  request jsonb NOT NULL,
  request_digest text NOT NULL,
  attempts_max bigint NOT NULL,
  attempts_made bigint NOT NULL,
  run_at_ms bigint NOT NULL,
  sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at_ms bigint NOT NULL,
  updated_at_ms bigint NOT NULL,
  published_at_ms bigint,
  lease_owner text,
  lease_token text,
  lease_expires_at_ms bigint,
  failure jsonb,
  PRIMARY KEY (namespace, id),
  CONSTRAINT better_effect_mq_outbox_nonempty CHECK (
    namespace <> '' AND id <> '' AND target <> '' AND request_digest <> ''
  ),
  CONSTRAINT better_effect_mq_outbox_protocol CHECK (protocol_version = 1),
  CONSTRAINT better_effect_mq_outbox_state CHECK (
    state IN ('pending', 'active', 'published', 'failed')
  ),
  CONSTRAINT better_effect_mq_outbox_counters CHECK (
    attempts_max >= 1 AND attempts_made >= 0 AND attempts_made <= attempts_max
  ),
  CONSTRAINT better_effect_mq_outbox_epoch_ms CHECK (
    run_at_ms BETWEEN 0 AND 9007199254740991
    AND created_at_ms BETWEEN 0 AND 9007199254740991
    AND updated_at_ms BETWEEN 0 AND 9007199254740991
    AND (published_at_ms IS NULL OR published_at_ms BETWEEN 0 AND 9007199254740991)
    AND (lease_expires_at_ms IS NULL OR lease_expires_at_ms BETWEEN 0 AND 9007199254740991)
  ),
  CONSTRAINT better_effect_mq_outbox_json CHECK (
    jsonb_typeof(request) = 'object'
    AND (failure IS NULL OR jsonb_typeof(failure) = 'object')
  ),
  CONSTRAINT better_effect_mq_outbox_tokens CHECK (
    (lease_owner IS NULL OR lease_owner <> '')
    AND (lease_token IS NULL OR lease_token <> '')
  ),
  CONSTRAINT better_effect_mq_outbox_active_lease CHECK (
    (state = 'active' AND lease_owner IS NOT NULL AND lease_token IS NOT NULL
      AND lease_expires_at_ms IS NOT NULL)
    OR (state <> 'active' AND lease_owner IS NULL AND lease_token IS NULL
      AND lease_expires_at_ms IS NULL)
  ),
  CONSTRAINT better_effect_mq_outbox_published_time CHECK (
    (state = 'published' AND published_at_ms IS NOT NULL)
    OR (state <> 'published' AND published_at_ms IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS better_effect_mq_outbox_claim_idx
  ON {{SCHEMA}}.better_effect_mq_outbox
  (namespace, state, run_at_ms ASC, sequence ASC, id COLLATE "C" ASC)
  WHERE state = 'pending';
CREATE INDEX IF NOT EXISTS better_effect_mq_outbox_active_lease_idx
  ON {{SCHEMA}}.better_effect_mq_outbox
  (namespace, lease_expires_at_ms ASC, sequence ASC, id COLLATE "C" ASC)
  WHERE state = 'active';
CREATE INDEX IF NOT EXISTS better_effect_mq_outbox_target_state_idx
  ON {{SCHEMA}}.better_effect_mq_outbox
  (namespace, target COLLATE "C" ASC, state, run_at_ms ASC, sequence ASC);
CREATE INDEX IF NOT EXISTS better_effect_mq_outbox_recent_idx
  ON {{SCHEMA}}.better_effect_mq_outbox
  (namespace, created_at_ms DESC, sequence DESC, id COLLATE "C" DESC);
CREATE INDEX IF NOT EXISTS better_effect_mq_outbox_digest_idx
  ON {{SCHEMA}}.better_effect_mq_outbox
  (namespace, request_digest COLLATE "C" ASC);
CREATE INDEX IF NOT EXISTS better_effect_mq_outbox_published_idx
  ON {{SCHEMA}}.better_effect_mq_outbox
  (namespace, published_at_ms DESC, sequence DESC, id COLLATE "C" DESC)
  WHERE state = 'published';
