-- better-effect-mq flow protocol v2 extension, migration 4.
-- This migration is additive and never rewrites migrations 001-003.
-- The adapter substitutes {{SCHEMA}} with one validated, quoted identifier.

ALTER TABLE {{SCHEMA}}.better_effect_mq_jobs
  ADD COLUMN IF NOT EXISTS parent jsonb,
  ADD COLUMN IF NOT EXISTS flow jsonb,
  ADD COLUMN IF NOT EXISTS flow_manifest_digest text,
  ADD COLUMN IF NOT EXISTS flow_lease_token text,
  ADD COLUMN IF NOT EXISTS flow_name text,
  ADD COLUMN IF NOT EXISTS flow_parent_store_key text,
  ADD COLUMN IF NOT EXISTS flow_depth bigint;

ALTER TABLE {{SCHEMA}}.better_effect_mq_jobs
  DROP CONSTRAINT IF EXISTS better_effect_mq_jobs_state;
ALTER TABLE {{SCHEMA}}.better_effect_mq_jobs
  ADD CONSTRAINT better_effect_mq_jobs_state CHECK (
    state IN ('waiting', 'delayed', 'active', 'waiting-children', 'completed', 'failed', 'cancelled')
  );
ALTER TABLE {{SCHEMA}}.better_effect_mq_jobs
  DROP CONSTRAINT IF EXISTS better_effect_mq_jobs_flow_json;
ALTER TABLE {{SCHEMA}}.better_effect_mq_jobs
  ADD CONSTRAINT better_effect_mq_jobs_flow_json CHECK (
    (parent IS NULL OR jsonb_typeof(parent) = 'object')
    AND (flow IS NULL OR jsonb_typeof(flow) = 'object')
    AND (flow_manifest_digest IS NULL OR flow_manifest_digest <> '')
    AND (flow_lease_token IS NULL OR flow_lease_token <> '')
    AND (flow_name IS NULL OR flow_name <> '')
    AND (flow_parent_store_key IS NULL OR flow_parent_store_key <> '')
    AND (flow_depth IS NULL OR flow_depth BETWEEN 1 AND 32)
  );

CREATE INDEX IF NOT EXISTS better_effect_mq_jobs_waiting_children_idx
  ON {{SCHEMA}}.better_effect_mq_jobs
  (namespace, state, updated_at_ms ASC, sequence ASC, id COLLATE "C" ASC)
  WHERE state = 'waiting-children';

CREATE TABLE IF NOT EXISTS {{SCHEMA}}.better_effect_mq_flow_children (
  namespace text NOT NULL,
  flow_id text NOT NULL,
  child_key text NOT NULL,
  name text NOT NULL,
  version bigint NOT NULL,
  store_key text NOT NULL,
  child_job_id text NOT NULL,
  request jsonb NOT NULL,
  status text NOT NULL,
  result jsonb,
  failure jsonb,
  cascaded boolean NOT NULL DEFAULT false,
  pending_since_ms bigint NOT NULL,
  PRIMARY KEY (namespace, flow_id, child_key),
  CONSTRAINT better_effect_mq_flow_children_parent_fk FOREIGN KEY (namespace, flow_id)
    REFERENCES {{SCHEMA}}.better_effect_mq_jobs(namespace, id) ON DELETE CASCADE,
  CONSTRAINT better_effect_mq_flow_children_values CHECK (
    namespace <> '' AND flow_id <> '' AND child_key <> '' AND name <> '' AND version > 0
    AND store_key <> '' AND child_job_id <> ''
  ),
  CONSTRAINT better_effect_mq_flow_children_status CHECK (
    status IN ('pending', 'completed', 'failed', 'cancelled')
  ),
  CONSTRAINT better_effect_mq_flow_children_json CHECK (
    jsonb_typeof(request) = 'object'
    AND (result IS NULL OR jsonb_typeof(result) IS NOT NULL)
    AND (failure IS NULL OR jsonb_typeof(failure) = 'object')
  ),
  CONSTRAINT better_effect_mq_flow_children_terminal CHECK (
    (status = 'pending' AND result IS NULL AND failure IS NULL)
    OR (status = 'completed' AND failure IS NULL)
    OR (status IN ('failed', 'cancelled'))
  ),
  CONSTRAINT better_effect_mq_flow_children_time CHECK (
    pending_since_ms BETWEEN 0 AND 9007199254740991
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS better_effect_mq_flow_children_job_idx
  ON {{SCHEMA}}.better_effect_mq_flow_children (namespace, child_job_id);
CREATE INDEX IF NOT EXISTS better_effect_mq_flow_children_pending_idx
  ON {{SCHEMA}}.better_effect_mq_flow_children
  (namespace, flow_id, pending_since_ms ASC, child_key COLLATE "C" ASC)
  WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS better_effect_mq_flow_children_cascade_idx
  ON {{SCHEMA}}.better_effect_mq_flow_children
  (namespace, flow_id, child_key COLLATE "C" ASC)
  WHERE status = 'cancelled' AND cascaded = false;

CREATE TABLE IF NOT EXISTS {{SCHEMA}}.better_effect_mq_flow_outbox (
  namespace text NOT NULL,
  id text NOT NULL,
  flow_name text NOT NULL,
  parent_store_key text NOT NULL,
  report jsonb NOT NULL,
  sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at_ms bigint NOT NULL,
  PRIMARY KEY (namespace, id),
  CONSTRAINT better_effect_mq_flow_outbox_values CHECK (
    namespace <> '' AND id <> '' AND flow_name <> '' AND parent_store_key <> ''
    AND created_at_ms BETWEEN 0 AND 9007199254740991
    AND jsonb_typeof(report) = 'object'
  )
);

CREATE INDEX IF NOT EXISTS better_effect_mq_flow_outbox_claim_idx
  ON {{SCHEMA}}.better_effect_mq_flow_outbox
  (namespace, sequence ASC, id COLLATE "C" ASC);
CREATE INDEX IF NOT EXISTS better_effect_mq_flow_outbox_route_idx
  ON {{SCHEMA}}.better_effect_mq_flow_outbox
  (namespace, parent_store_key COLLATE "C" ASC, sequence ASC, id COLLATE "C" ASC);
